### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by ir4y** [beda-software/fhir-client-testing-tool#5]
- [x] Document terminology 
- [x] Provide an interaction diagram for the solution
- [x] Implement test that validate resource via validator wrapper.
-------------------
- [x] Create session api should return baseUrl
- [x] Reactive API that shows test progress
- [x] API to show list of available test suites
- [x] Run specific describe or specific test, if we run describe it should support reactive test reporting
- [x] Download test report for provided test run
- [x] API to get session information, including a total number of recorded requests
- [x] API that returns requests for provided session id with search support

**Comment by projkov** [comment]
https://docs.google.com/document/d/1sXO2eIDQohRoZbyMB16hXncKVd3J507BVKnHfOlAPsM/edit?usp=sharing

**Comment by projkov** [comment]
Rename /app to /proxy
